version: '2'

#here we create the volumes. We keep the same names for backup purpouses
volumes:
  vaultwarden:
    name: vaultwarden
  npm:
    name: npm
  adguard:
    name: adguard

#we put all containers under the same newtwork
networks:
  securityNetwork:
    driver: bridge
    name: security_network
    ipam:
      config:
        - subnet: 10.3.0.0/16
  additionalNetwork:
    driver: bridge
    name: add_network
    ipam:
      config:
        - subnet: 10.7.0.0/16
  managementNetwork:
    driver: bridge
    name: management_network
    ipam:
      config:
        - subnet: 10.6.0.0/16
services:
  #This project was known as Bitwarden_RS and has been renamed to separate itself from the official Bitwarden server in the hopes of avoiding confusion and trademark/branding issues.
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ADMIN_TOKEN=${BW_TOKEN}
    volumes:
      - vaultwarden:/data
    ports:
      - 280:80
    networks:
      - internal-network
    restart: always
  #nginx-proxy-manager: Expose your services easily and securely.
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - 'npm:/data'
      - 'npm:/etc/letsencrypt'
    networks:
      - securityNetwork
      - additionalNetwork
      - managementNetwork
    restart: always
  #ad-adguard
  adguard:
    container_name: adguardhome
    image: adguard/adguardhome
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - adguard:/opt/adguardhome/work
      - adguard:/opt/adguardhome/conf
    #    ports:
    #      - 53:53/tcp
    #      - 53:53/udp
    #      - 67:67/udp
    #      - 68:68/tcp
    #      - 68:68/udp
    #      - 3000:3000/tcp
    network_mode: host
    restart: always